version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '2501:80'
        volumes:
            - ./public:/code
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
